name: oracle_build

on:
  push:
    branches:
      - v4 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ORACLE_SSH }}  

      - name: Run build quartz
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@168.75.93.254 << 'EOF'
              bash -c "cd /home/ubuntu/quartz && git pull && npx quartz build && exit"
          EOF
