name: Repository Dispatch

on:
  repository_dispatch:
    types:
      - content-updated

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Quartz
        run: npx quartz build
